### ISSUE TITLE
Question about something else

### ISSUE THREAD

**Issue by Darker-Ink** [RobinSchapendonk/personal-bot#1]
Since idk where else to reach you I'm going to make a issue here I guess? anyway I saw on your account you had a [mongoose](https://github.com/RobinSchapendonk/discord-mongoose-systems) system but idk if you privated it or not and I will just like to know if that is ig with me asking! Thank you if you ever answer!

**Comment by RobinSchapendonk** [comment]
I had multiple separate Discord bots repos, I merged them all into one repo. You can find the mongoose repo here: https://github.com/RobinSchapendonk/discord-bots/tree/master/mongodb

**Comment by Darker-Ink** [comment]
> I had multiple separate Discord bots repos, I merged them all into one repo. You can find the mongoose repo here: https://github.com/RobinSchapendonk/discord-bots/tree/master/mongodb

Oh thank you!
